export interface Room {
    id?: number;         // Optional for new rooms (auto-generated by backend)
    number: string;
    type: string;
    capacity: number;
    pricePerNight: number;
    equipments: string;
  }