spring.datasource.url=jdbc:postgresql://ep-young-sun-abyn57fm-pooler.eu-west-2.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_z7dqeKVPCEr2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
